name: Build
on: [push]
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: pip install pyinstaller
      - run: pyinstaller --onefile CPM.py
      - uses: actions/upload-artifact@v4
        with:
          name: windows-exe
          path: dist/CPM.exe
